### ISSUE TITLE
Crear efemerides

### ISSUE THREAD

**Issue by YPEZOA** [aether7/civi-conecta-server#29]
curl 'https://civi-server-dev.adaptable.app/events/3' \
  -H 'authority: civi-server-dev.adaptable.app' \
  -H 'accept: */*' \
  -H 'accept-language: es-ES,es;q=0.9,la;q=0.8,gl;q=0.7' \
  -H 'content-type: application/json' \
  -H 'origin: http://localhost:3000' \
  -H 'referer: http://localhost:3000/' \
  -H 'sec-ch-ua: "Chromium";v="110", "Not A(Brand";v="24", "Google Chrome";v="110"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoiY2F0YWxpbmFAY2l2aWNvbmVjdGEuY2wiLCJuYW1lIjoiQ2F0YWxpbmEiLCJyb2xlIjoiQWRtaW5pc3RyYXRvciIsImFjdGl2ZSI6MSwicGFzc3dvcmQiOiI1N2ZmNWQ4NTQ2MDI1MzZjNjdjMWM1MTZmYjk4YzA1MzlmZjI2NTU0NDQwYjdlMzQ4MGNkMmExMDAwOGMxZDUyIiwidXVpZCI6ImVhMDNiNmZhLWFiNzMtNDRjMS05NzNhLWFjZjY0ZTY0ZDM5NyJ9LCJpYXQiOjE2NzgyMTI5MjksImV4cCI6MTY3ODgxNzcyOX0.PVUSWdCvjNvO1aLk_8Ev99ysT5MjJPdGjsybv3TEMSw' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36' \
  --data-raw '{"title":"titulo de la efemeride","description":"ljkasldkjasdl","objective":"Sin objetivos","date":"2023-05-06","grade":"1","planning":{"topic":"ldjkasljasdkl","materials":{"teacher":["uno","dos"],"student":["uno","dos"]},"startActivity":"ljkasldjkasld","mainActivity":"lkajsldjaksd","endActivity":"ldjalsdjkaklsdj","keywords":["alsdjalsdjk"]},"unit":null}' \
  --compressed

**Comment by aether7** [comment]
otra cosa mr @YPEZOA para esto, solo debe recibir como fecha dia y mes
![image](https://user-images.githubusercontent.com/1638567/223558269-c691f4e6-a3c9-4615-af4c-98bbfc57d4a7.png)

en lo que me enviaste se envia mes y año, asi que atento 👀
