### ISSUE TITLE
Navegar a planificacion del evento seleccionado, hasta el momento puedo solo con 2 de los 4 ingresar a su planificacion

### ISSUE THREAD

**Issue by YPEZOA** [aether7/civi-conecta-server#31]
curl 'https://civi-server-dev.adaptable.app/lessons/12' \
  -H 'authority: civi-server-dev.adaptable.app' \
  -H 'accept: */*' \
  -H 'accept-language: es-ES,es;q=0.9,la;q=0.8,gl;q=0.7' \
  -H 'content-type: application/json' \
  -H 'origin: http://localhost:3000' \
  -H 'referer: http://localhost:3000/' \
  -H 'sec-ch-ua: "Chromium";v="110", "Not A(Brand";v="24", "Google Chrome";v="110"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoiY2F0YWxpbmFAY2l2aWNvbmVjdGEuY2wiLCJuYW1lIjoiQ2F0YWxpbmEiLCJyb2xlIjoiQWRtaW5pc3RyYXRvciIsImFjdGl2ZSI6MSwicGFzc3dvcmQiOiI1N2ZmNWQ4NTQ2MDI1MzZjNjdjMWM1MTZmYjk4YzA1MzlmZjI2NTU0NDQwYjdlMzQ4MGNkMmExMDAwOGMxZDUyIiwidXVpZCI6ImVhMDNiNmZhLWFiNzMtNDRjMS05NzNhLWFjZjY0ZTY0ZDM5NyJ9LCJpYXQiOjE2NzgyMTI5MjksImV4cCI6MTY3ODgxNzcyOX0.PVUSWdCvjNvO1aLk_8Ev99ysT5MjJPdGjsybv3TEMSw' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36' \
  --compressed

**Comment by aether7** [comment]
@YPEZOA segun lo que veo, estas intentando acceder a la lesson 12, la cual no existe, sin embargo el evento num 12 si existe, puedes revisar si lo que quieres es acceder al evento o a los datos ?. Ya que para este caso los datos de una lesson seria segun veo la lesson 7

**Comment by aether7** [comment]
para acceder a los datos del evento que tambien tienen la planificacion puedes usar el endpoint

http://host/events/:eventTypeId/:eventId ---> con esto obtienes con el id 12 los datos

**Comment by aether7** [comment]
aqui un ejemplo de como llea con lo que te menciono

![image](https://user-images.githubusercontent.com/1638567/223565692-52e3ff1f-d711-47fe-b987-2281293e145c.png)
