### ISSUE TITLE
Zona publica / Perfil docente / Respuestas criticas

### ISSUE THREAD

**Issue by Mentalchaos** [aether7/civi-conecta-server#41]
Es necesario generar un endpoint que encuentre las 3 respuestas mas criticas basadas en el puntaje en promedio de todos los alumnos para distintas preguntas en particular

Se requiere el numero de pregunta y la pregunta para poder rellenar esa seccion

<img width="608" alt="Captura de Pantalla 2023-04-19 a la(s) 17 08 47" src="https://user-images.githubusercontent.com/8239243/233200869-0f7a168c-ba8b-48b5-9350-572573465c57.png">

**Comment by aether7** [comment]
subido a la rama
