### ISSUE TITLE
Zona publica / Perfil docente / Analisis encuesta estudiantes

### ISSUE THREAD

**Issue by Mentalchaos** [aether7/civi-conecta-server#42]
Se requiere un endpoint para poder generar este grafico

La data corresponde al % de alumnos que contestaron cada alternativa de una pregunta determinada

Se puede llegar a este modal clickeando el boton de "ver mas", en la seccion de respuestas criticas en el perfil del profesor

<img width="559" alt="Captura de Pantalla 2023-04-19 a la(s) 17 08 57" src="https://user-images.githubusercontent.com/8239243/233201452-a5af42f9-8d03-4301-b60f-ac3f338cc3de.png">

**Comment by aether7** [comment]
ya esta mezclado y tambien se encuentra como se utiliza en la documentacion 😜
