### ISSUE TITLE
Zona publica / Informe de resultados

### ISSUE THREAD

**Issue by Mentalchaos** [aether7/civi-conecta-server#43]
Se requiere generar un endpoint para traer la data para poder generar estos graficos

Cada uno de los elementos trae cada una de las preguntas y tambien el % promedio de respuestas de cada alumno en cada una de sus respuestas

Esto corresponde a traer esta data para todas las unidades/temas que posea el curso

<img width="741" alt="Captura de Pantalla 2023-04-19 a la(s) 17 14 04" src="https://user-images.githubusercontent.com/8239243/233202101-a63c2e0d-90e0-4599-ab48-2b4df3480b3f.png">

**Comment by aether7** [comment]
ya esta commiteado desde ya esta version
