### ISSUE TITLE
Zona Publica / Dashboard

### ISSUE THREAD

**Issue by Mentalchaos** [aether7/civi-conecta-server#44]
Se requiere generar un endpoint que pueda traer las unidades ordenadas de acuerdo al resultado de las encuestas de docente y del estudiante, basandose en el promedio de las respuestas de los alumnos y la del profesor

<img width="695" alt="Captura de Pantalla 2023-04-19 a la(s) 17 20 30" src="https://user-images.githubusercontent.com/8239243/233203257-cee60697-286a-40fd-96c3-67910bf93cc6.png">

**Comment by aether7** [comment]
ya fue liberada en el ultimo release
